const actions = {

  DEFAULT: "DEFAULT",
  DEFAULT_RESULT: "DEFAULT_RESULT",
  DEFAULT_ERROR: "DEFAULT_ERROR",


  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_RESULT_SUCCESS: "LOGIN_USER_RESULT_SUCCESS",
  LOGIN_USER_RESULT_ERROR: "LOGIN_USER_RESULT_ERROR",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",

  REGISTER_EMAIL: "REGISTER_EMAIL",
  REGISTER_EMAIL_RESULT_SUCCESS: "REGISTER_EMAIL_RESULT_SUCCESS",
  REGISTER_EMAIL_RESULT_ERROR: "REGISTER_EMAIL_RESULT_ERROR",
  REGISTER_EMAIL_ERROR: "REGISTER_EMAIL_ERROR",

  GET_INDUSTRIES:"GET_INDUSTRIES",
  GET_INDUSTRIES_RESULT:"GET_INDUSTRIES_RESULT",
  GET_INDUSTRIES_ERROR:"GET_INDUSTRIES_ERROR",

  GET_PRODUCTS:"GET_PRODUCTS",
  GET_PRODUCTS_RESULT:"GET_PRODUCTS_RESULT",
  GET_PRODUCTS_ERROR:"GET_PRODUCTS_ERROR",

  GET_COUNTRIES:"GET_COUNTRIES",
  GET_COUNTRIES_RESULT:"GET_COUNTRIES_RESULT",
  GET_COUNTRIES_ERROR:"GET_COUNTRIES_ERROR",

  FOGET_PASSWORD:"FOGET_PASSWORD",
  FOGET_PASSWORD_RESULT_SUCCESS:"FOGET_PASSWORD_RESULT_SUCCESS",
  FOGET_PASSWORD_RESULT_ERROR:"FOGET_PASSWORD_RESULT_ERROR",
  FOGET_PASSWORD_ERROR:"FOGET_PASSWORD_ERROR",

  UPDATE_PASSWORD:"UPDATE_PASSWORD",
  UPDATE_PASSWORD_RESULT_SUCCESS:"UPDATE_PASSWORD_RESULT_SUCCESS",
  UPDATE_PASSWORD_RESULT_ERROR:"UPDATE_PASSWORD_RESULT_ERROR",
  UPDATE_PASSWORD_ERROR:"UPDATE_PASSWORD_ERROR",


  CLEAR_PROPS:"CLEAR_PROPS",

  updatePassword:(data)=>({
    type: actions.UPDATE_PASSWORD,
    data
   
  }),


  fogetPassword:(data)=>({
    type: actions.FOGET_PASSWORD,
    data
   
  }),


  getCountries:()=>({
    type: actions.GET_COUNTRIES,
   
  }),

  getProducts: (data) => ({
    type: actions.GET_PRODUCTS,
    data
  }),

  getIndustries: (data) => ({
    type: actions.GET_INDUSTRIES,
    data
  }),

  registerEmail: (data) => ({
    type: actions.REGISTER_EMAIL,
    data
  }),

  loginUser: (data) => ({
    type: actions.LOGIN_USER,
    data
  }),


  defaultFunc: (value) => ({
    type: actions.DEFAULT,
    value
  }),

  clearProps: () =>({
    type: actions.CLEAR_PROPS,
    
  }),
};

export default actions;