const actions = {

  DEFAULT: "DEFAULT",
  DEFAULT_RESULT: "DEFAULT_RESULT",
  DEFAULT_ERROR: "DEFAULT_ERROR",

 

  GET_FAVOURITE_VEDIOS:"GET_FAVOURITE_VEDIOS",
  GET_FAVOURITE_VEDIOS_RESULT_SUCCESS:"GET_FAVOURITE_VEDIOS_RESULT_SUCCESS",
  GET_FAVOURITE_VEDIOS_RESULT_ERROR:"GET_FAVOURITE_VEDIOS_RESULT_ERROR",
  GET_FAVOURITE_VEDIOS_ERROR:"GET_FAVOURITE_VEDIOS_ERROR",

  GET_FAVOURITE_DOCUMENTS:"GET_FAVOURITE_DOCUMENTS",
  GET_FAVOURITE_DOCUMENTS_RESULT_SUCCESS:"GET_FAVOURITE_DOCUMENTS_RESULT_SUCCESS",
  GET_FAVOURITE_DOCUMENTS_RESULT_ERROR:"GET_FAVOURITE_DOCUMENTS_RESULT_ERROR",
  GET_FAVOURITE_DOCUMENTS_ERROR:"GET_FAVOURITE_DOCUMENTS_ERROR",

  SELECT_FAVOURITE_VIDEO:"SELECT_FAVOURITE_VIDEO",
  SELECT_FAVOURITE_VIDEO_RESULT_SUCCESS:"SELECT_FAVOURITE_VIDEO_RESULT_SUCCESS",
  SELECT_FAVOURITE_VIDEO_RESULT_ERROR:"SELECT_FAVOURITE_VIDEO_RESULT_ERROR",
  SELECT_FAVOURITE_VIDEO_ERROR:"SELECT_FAVOURITE_VIDEO_ERROR",

  SELECT_FAVOURITE_DOCUMENTS:"SELECT_FAVOURITE_DOCUMENTS",
  SELECT_FAVOURITE_DOCUMENTS_RESULT_SUCCESS:"SELECT_FAVOURITE_DOCUMENTS_RESULT_SUCCESS",
  SELECT_FAVOURITE_DOCUMENTS_RESULT_ERROR:"SELECT_FAVOURITE_DOCUMENTS_RESULT_ERROR",
  SELECT_FAVOURITE_DOCUMENTS_ERROR:"SELECT_FAVOURITE_DOCUMENTS_ERROR",

  GET_VIDEO_PLAYER_LIST:"GET_VIDEO_PLAYER_LIST",
  GET_VIDEO_PLAYER_LIST_RESULT_SUCCESS:"GET_VIDEO_PLAYER_LIST_RESULT_SUCCESS",
  GET_VIDEO_PLAYER_LIST_RESULT_ERROR:"GET_VIDEO_PLAYER_LIST_RESULT_ERROR",
  GET_VIDEO_PLAYER_LIST_ERROR:"GET_VIDEO_PLAYER_LIST_ERROR",



  CLEAR_PROPS:"CLEAR_PROPS",

  getVedioPlayerList:(access_token,categoryid,vedioid)=>({
    type: actions.GET_VIDEO_PLAYER_LIST,
     access_token,
     categoryid,
     vedioid
   }),



  selectFavouriteVedio:(access_token,vedioid)=>({
    type: actions.SELECT_FAVOURITE_VIDEO,
    access_token,
    vedioid
  }),

  selectFavouriteDocuments:(access_token,docid)=>({
    type: actions.SELECT_FAVOURITE_DOCUMENTS,
    access_token,
    docid
  }),


  getFavouriteVedioList:(access_token)=>({
    type: actions.GET_FAVOURITE_VEDIOS,
    access_token
   
  }),

  getFavouriteDocumentList:(access_token)=>({
    type: actions.GET_FAVOURITE_DOCUMENTS,
    access_token
   
  }),

  clearProps: () =>({
    type: actions.CLEAR_PROPS,
    
  }),

  defaultFunc: (value) => ({
    type: actions.DEFAULT,
    value
  }),
};

export default actions;